### ISSUE TITLE
Can't build pyo3 projects on Python 2.7 / Windows 10

### ISSUE THREAD

**Issue by msanders** [PyO3/pyo3#215] opened 2018-09-08 06:08 UTC
Encountered this today when trying to update my project to the latest pyo3 version and package a new binary wheel.

### 🌍 Environment

 - OS: Windows 10 (both 64 and 32-bit).
 - Python version: Python 2.7.15
 - Python installation method: Windows executable installer.
 - Rust version: rustc 1.30.0-nightly (6e0f1cc15 2018-09-05)

### 💥 Reproducing

To reproduce, attempt to build the word-count example in the pyo3 repo on Windows 10 using Python 2.7 via `py -2.7 setup.py build`. You should receive the following error:

```
error: failed to run custom build command for `pyo3 v0.5.0 (file:///Z:/pyo3)`
process didn't exit successfully: `Z:\pyo3\target\release\build\pyo3-9bd5a43a4e1f40fc\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to run python interpreter:\n\nThe system cannot find the file specified. (os error 2)"', libcore\result.rs:983:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: cargo failed with code: 101
```

I also have Python 3.7 and 3.6 installed (possible they could be conflicting, but not sure how to workaround).

**Comment by macisamuele** [comment] 2018-09-08 10:28
@msanders Could you run the build command with `RUST_BACKTRACE` environmental variable set to `full` and posting the whole stacktrace?

While working on a project based on pyo3 ([rust-swagger-validator](https://github.com/macisamuele/rust-swagger-validator)) I faced similar issues during appveyor tests.

In my case, the issue was related to the fact that the windows linker was not able to find the python libraries to link against. Build failure was caused by the fact that I'm building the rust module within a virtual environment (provided by tox) and because some build environmental variables (needed by the `msvc` compiler were not set).

To workaround the issue with:
 * the virtual environment I'm installing a "custom" virtualenv version ([virtualenv fork](https://github.com/macisamuele/virtualenv/tree/maci-pr-1023-backport)) as the issue is known in pypa /virtualenv and a pull request has already been issued ([pypa/virtualenv PR#1023](https://github.com/pypa/virtualenv/pull/1023 )). Doing it allows the linker to find the python libraries and so to be able to have a green build
 * the `msvc` environmental varialbes I followed [Supporting Windows using AppVetoy guide](https://packaging.python.org/guides/supporting-windows-using-appveyor/#testing-with-tox) by running `CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64` for 64 bits builds (replace `amd64` with `x86` for 32 bits builds)

NOTE: the second bullet point could be not needed for your case, but I guess that the first one is definitely needed if you have multiple python versions installed on your Windows machine.

I hope that those informations help you out.

**Comment by msanders** [comment] 2018-09-09 00:06
Hi @macisamuele, thanks for the help. Here is the full backtrace:

```
error: failed to run custom build command for `pyo3 v0.5.0 (file:///Z:/pyo3)`
process didn't exit successfully: `Z:\pyo3\target\release\build\pyo3-9bd5a43a4e1f40fc\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "failed to run python interpreter:\n\nThe system cannot find the file specified. (os error 2)"', libcore\result.rs:983:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:391
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:326
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:77
  10: core::result::unwrap_failed
  11: alloc::alloc::box_free
  12: <T as core::any::Any>::get_type_id
  13: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  14: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:103
  16: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  18: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  19: main
  20: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  21: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  22: BaseThreadInitThunk
  23: RtlUserThreadStart

error: cargo failed with code: 101
```

I actually wasn't using `virtualenv`. When I do (with or without the two workarounds you listed), I receive the following:

```
   Compiling word-count v0.1.0 (file:///Z:/pyo3/examples/word-count)
     Running `rustc --crate-name word_count examples\word-count\src\lib.rs --crate-type cdylib --emit=dep-info,link -C opt-level=3 --crate-type cdylib --cfg "feature=\"pyo3\"" -C metadata=b588bda2916d9f63 --out-dir Z:\pyo3\target\release\deps -L dependency=Z:\pyo3\target\release\deps --extern pyo3=Z:\pyo3\target\release\deps\libpyo3-ff4e61af0e27b1f4.rlib --extern rayon=Z:\pyo3\target\release\deps\librayon-c891563e5babb987.rlib -L native=Z:\pyo3\examples\word-count\libs`
error: linking with `link.exe` failed: exit code: 1181
  = note: LINK : fatal error LNK1181: cannot open input file 'python27.lib'

error: aborting due to previous error

error: Could not compile `word-count`.

Caused by:
  process didn't exit successfully: `rustc --crate-name word_count examples\word-count\src\lib.rs --crate-type cdylib --emit=dep-info,link -C opt-level=3 --crate-type cdylib --cfg "feature=\"pyo3\"" -C metadata=b588bda2916d9f63 --out-dir Z:\pyo3\target\release\deps -L dependency=Z:\pyo3\target\release\deps --extern pyo3=Z:\pyo3\target\release\deps\libpyo3-ff4e61af0e27b1f4.rlib --extern rayon=Z:\pyo3\target\release\deps\librayon-c891563e5babb987.rlib -L native=Z:\pyo3\examples\word-count\libs` (exit code: 1)
error: cargo failed with code: 101
```

**Comment by macisamuele** [comment] 2018-09-09 00:42
@msanders Checking the first stacktrace I see
`"failed to run python interpreter:\n\nThe system cannot find the file specified. (os error 2)"'`
The error message is generated by pyo3 build script
https://github.com/PyO3/pyo3/blob/d92e5222439065458af613a79b18939a685aef07/build.rs#L178

This means that while running the `cargo build` command (probably via `setuptools-rust`) is not clear which is your python interpreter.

Checking the second stacktrace I see that you have a linking problem. Linking is the last step of the compilation chain
![http://i.imgur.com/ZVBXFHm.jpg](http://i.imgur.com/ZVBXFHm.jpg)
Image from https://users.rust-lang.org/t/the-big-picture-of-compilation-in-rust/6380/5

This means that you were able to compile the the bytecode of all the project and so the build script succeeded. So applying the workarounds you moved a bit further into the compilation process.

Maybe I forgot to mention it, but you need to add to the `LIB` environment variable the libraries of your target python interpreter (example on https://github.com/macisamuele/rust-swagger-validator/blob/master/.appveyor.yml#L55)

**Comment by konstin** [comment] 2018-09-09 16:48
Those are distinct problems, so I'm going to split my answer in two parts

## `py -2.7 setup.py build`

The problem here is a bug is that setuptools-rust tells the build script to use python 2, and the build script (incorrectly) assumes that the interpreter lives at `python2` instead of `py -2.7`. This can be fixed by settings `PYTHON_SYS_EXECUTABLE` to `py -2.7 -c "import sys; print(sys.executable)"`, which normally is `C:\Python2.7\python.exe`. pyo3-pack always sets `PYTHON_SYS_EXECUTABLE`, so it's not affected by that. A proper fix to that would both rewrite the interpreter detection in `build.rs` (which is quiet messy right now) and make setuptools-rust set `PYTHON_SYS_EXECUTABLE` to `sys.executable`.

## Building in virtualenvs

To build the final cdylib, which is a `.dll` on windows, the linker needs a file called `pythonxy.lib`, where x and y are the major and minor version. It's a bug in virtualenv that this file is neither copied nor its location listed anywhere. (Thanks @macisamuele for digging up https://github.com/pypa/virtualenv/pull/1023 - I wouldn't found that otherwise). Using system python and/or setting `LIB` seems to be the best option. I'm a bit confused that `SET LIB=%PYTHON%\Lib;%LIB%` works in appveyor though. On machine (pretty fresh windows installation with python installed from python.org) I had to use `%PYTHON%\libs` instead of `%PYTHON%\Lib`.

**Comment by konstin** [comment] 2018-09-09 16:50
I've added a small section about linking and environment variables in 9405ffa3b9f14284697e2a7339fcd97c31e35d33

**Comment by msanders** [comment] 2018-09-09 17:37
Thanks @konstin, your setting fixed the issue for me. Will check out the virtualenv workaround once I move to appveyor.

**Closed** 2019-02-10 19:26 UTC
Labels: Waiting for response
