### ISSUE TITLE
Document support for integer protocol

### ISSUE THREAD

**Issue by thedrow** [PyO3/pyo3#500] opened 2019-06-02 13:02 UTC
Just like we do support `__bool__` we should support `__int__`.

**Comment by thedrow** [comment] 2019-06-04 10:22
I tried the following patch:
```diff
diff --git a/pyo3-derive-backend/src/defs.rs b/pyo3-derive-backend/src/defs.rs
index b152324e..d32516fe 100644
--- a/pyo3-derive-backend/src/defs.rs
+++ b/pyo3-derive-backend/src/defs.rs
@@ -65,6 +65,11 @@ pub const OBJECT: Proto = Proto {
             pyres: false,
             proto: "pyo3::class::basic::PyObjectBoolProtocol",
         },
+        MethodProto::Unary {
+            name: "__int__",
+            pyres: true,
+            proto: "pyo3::class::basic::PyObjectIntProtocol",
+        },
         MethodProto::Binary {
             name: "__richcmp__",
             arg: "Other",
diff --git a/src/class/basic.rs b/src/class/basic.rs
index ed71e2d9..b7a2a19b 100644
--- a/src/class/basic.rs
+++ b/src/class/basic.rs
@@ -92,6 +92,13 @@ pub trait PyObjectProtocol<'p>: PyTypeInfo {
         unimplemented!()
     }
 
+    fn __int__(&'p self) -> Self::Result
+    where
+        Self: PyObjectIntProtocol<'p>,
+    {
+        unimplemented!()
+    }
+
     fn __bytes__(&'p self) -> Self::Result
     where
         Self: PyObjectBytesProtocol<'p>,
@@ -140,6 +147,10 @@ pub trait PyObjectHashProtocol<'p>: PyObjectProtocol<'p> {
 pub trait PyObjectBoolProtocol<'p>: PyObjectProtocol<'p> {
     type Result: Into<PyResult<bool>>;
 }
+pub trait PyObjectIntProtocol<'p>: PyObjectProtocol<'p> {
+    type Success: IntoPyObject;
+    type Result: Into<PyResult<Self::Success>>;
+}
 pub trait PyObjectBytesProtocol<'p>: PyObjectProtocol<'p> {
     type Success: IntoPyObject;
     type Result: Into<PyResult<Self::Success>>;
diff --git a/tests/test_dunder.rs b/tests/test_dunder.rs
index 80a82fa2..787e3a44 100644
--- a/tests/test_dunder.rs
+++ b/tests/test_dunder.rs
@@ -127,6 +127,9 @@ impl PyObjectProtocol for Comparisons {
     fn __bool__(&self) -> PyResult<bool> {
         Ok(self.val != 0)
     }
+    fn __int__(&self) -> PyResult<i32> {
+        Ok(self.val)
+    }
 }
 
 #[test]
@@ -144,6 +147,7 @@ fn comparisons() {
 
     py_assert!(py, one, "bool(one) is True");
     py_assert!(py, zero, "not zero");
+    py_assert!(py, one, "int(one) == 1");
 }
 
 #[pyclass]
```

But the test panics:
```
thread 'comparisons' panicked at 'assert int(one) == 1
: ()', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libcore/result.rs:827
  10: test_dunder::comparisons
             at tests/test_dunder.rs:150
  11: test_dunder::comparisons::{{closure}}
             at tests/test_dunder.rs:136
  12: core::ops::function::FnOnce::call_once
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libcore/ops/function.rs:231
  13: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/liballoc/boxed.rs:704
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  15: test::run_test::run_test_inner::{{closure}}
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/panicking.rs:272
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
```

Any help is appreciated.

**Comment by Alexander-N** [comment] 2019-06-04 23:19
I think `__int__` is part of the PyNumberProtocol:

```rust
#[pyproto]
impl PyNumberProtocol for Comparisons {
    fn __int__(&self) -> PyResult<i32> {
        Ok(self.val)
    }
}
```

**Comment by thedrow** [comment] 2019-06-05 07:51
Oh. It's not documented anywhere as far as I can see.

**Comment by davidhewitt** [comment] 2020-08-06 13:40
Closing as duplicate of #1032

**Closed by davidhewitt** 2020-08-06 13:40 UTC
Labels: documentation
