### ISSUE TITLE
__new__ and __init__ get no docstring

### ISSUE THREAD

**Issue by twuebi** [PyO3/pyo3#553] opened 2019-07-21 21:16 UTC
I am trying to add my doc-string and an explicit signature for `__new__` and `__init__` to `Foo`:

~~~rust
/// Foo(arg1, arg2)
/// --
///
/// A Foo
#[pyclass(name=Foo)]
pub struct PyFoo {
    inner: Rc<RefCell<Foo>>,
}

#[pymethods]
impl PyFoo {
    /// __new__(arg1, arg2)
    /// --
    ///
    /// Construct a new Foo
    #[new]
    fn __new__(
        obj: &PyRawObject,
        arg1: Vec<&str>,
        arg2: Vec<&str>
    ) -> PyResult<()> {
...
}
~~~

So far, I'm getting the call signature of `Foo` via `inspect.signature(Foo)` or with IPython `Foo?` but not through `help(Foo)`. Both `__new__` and `__init__` remain with their generic doc-strings and signatures defined in [typeobject.c](https://github.com/python/cpython/blob/5623ac87bbe5de481957eca5eeae06347612fbeb/Objects/typeobject.c#L6982). 

As far as I understand, CPython expects functions for `tp_new` and `tp_init` which is why the `ml_doc` fields of their `PyMethodDef` get discarded in `pyo3::type_object::py_class_method_defs`. Is there some other way to modify the doc-strings of these built-ins?

**Comment by twuebi** [comment] 2019-07-22 08:58
The init signature has been added to `help(type)` on some version >3.6.5 which I am on:

https://github.com/python/cpython/commit/ccb5f3cee9ebb5f20e33f31432a46579f8e9bf8e#diff-cbbbf1954ca2586f5d1d6241674fab9a

It still would be nice to be able to set the doc strings though.

**Comment by davidhewitt** [comment] 2024-10-11 20:28
Closing as duplicate of the (newer, more discussed) #4326

**Closed by davidhewitt** 2024-10-11 20:28 UTC
