### ISSUE TITLE
Coverage error on travis

### ISSUE THREAD

**Issue by kngwyu** [PyO3/pyo3#439] opened 2019-04-17 10:01 UTC
E.g., see https://travis-ci.org/PyO3/pyo3/jobs/521167916

What's happening?

cc: @althonos

**Comment by konstin** [comment] 2019-04-17 15:53
While I don't know the cause, this doesn't seem to happen on 3.5; Would it be an option to only collect coverage from 3.5, as afaik there's no real difference in coverage between the version?

**Comment by pganssle** [comment] 2019-04-17 16:12
@konstin The `datetime` stuff around `fold` is Python 3.6 -only. I will soon be adding some Python 3.7+ features as well, so I think it would be best to find the fix.

Can anyone reproduce it locally? If not, maybe we can do a rough "git bisect" by making a PR that reverts a bunch of commits and play with the number of reverted commits until we find the one that breaks it (assuming it's not broken because of something on Travis or codecov's end).

**Comment by konstin** [comment] 2019-04-17 16:46
According to the [travis history](https://travis-ci.org/PyO3/pyo3/builds) it's broken since #432, but I doubt there's any problem with that pull request. Also travis fails to show any proper error, which makes this weird.

**Comment by pganssle** [comment] 2019-04-17 17:35
I think maybe you have to e-mail Travis to request it (that I think was the procedure when I did it, very early on in this feature's life), but it's possible to run Travis in debug mode if you can't reproduce locally: https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by konstin** [comment] 2019-04-17 17:51
Having spent much time debugging ci services and especially travis ci in projects has drained my motivation to put more than the minimal effort into fixing this (which would be limiting coverage to 3.5). If someone else however is willing to work on this, I'd be happy to help.

FWIW you can also pull their docker container and copy&paste the commands for reproducing, which is kinda convenient. I haven't tried debug mode yet though.

**Comment by pganssle** [comment] 2019-04-23 23:57
If this is a Travis-specific issue, it might make sense to migrate to Azure Pipelines. Microsoft has been making a big push for them in the open source world lately, so the speed and quality of the builds is pretty high.

**Comment by konstin** [comment] 2019-04-28 08:53
Azure pipelines look really promising and I'd be happy to try it out. However I don't think the coverage error is travis ci's fault and also azure pipelines likely still has some rough edges.

**Comment by Alexander-N** [comment] 2019-05-15 22:22
The error seems to be gone, maybe we can close this issue?

**Comment by kngwyu** [comment] 2019-06-04 13:44
Coverage is broken again in #503(maybe because of trybuild?).
So.. how about stopping the use of coverage?
Honestly I don't think it is very important and meaningful for us.

**Comment by Alexander-N** [comment] 2019-06-04 20:14
Since the coverage seems to be a constant hassle, I wouldn't be opposed to removing it again.

**Comment by althonos** [comment] 2019-06-04 21:37
Or other option, make the coverage script fail silently, so that it does not make the whole build a failure: this would allow the coverage to be reported still *most of the time*.

**Comment by konstin** [comment] 2019-06-05 09:51
The build failure in #503 is a bug in trybuild: https://github.com/dtolnay/trybuild/issues/14

I agree with @althonos that we should just make that script an allowed failure. Coverage can be useful sometimes, even though we might want to remove the badge from the readme.

**Comment by konstin** [comment] 2019-07-15 10:14
Coverage has been allowed to fail for some time

**Closed by konstin** 2019-07-15 10:14 UTC
Labels: Continous Integration
