### ISSUE TITLE
Why `pointer being freed was not allocated` was raised here?

### ISSUE THREAD

**Issue by mejrs** [PyO3/pyo3#2354] opened 2022-05-03 10:14 UTC
### Discussed in https://github.com/PyO3/pyo3/discussions/2353

<div type='discussions-op-text'>

<sup>Originally posted by **tushushu** May  3, 2022</sup>
Hi there,
Below is my pyclasses, and the codes unrelated are omitted:

Base trait
```Rust
pub trait List<T>
where
    T: PartialEq + Clone,
    Self: Sized,
{
    // Arrange the following methods in alphabetical order.

    fn _new(vec: Vec<T>, hset: HashSet<usize>) -> Self;

    fn filter(&self, condition: &BooleanList) -> Self {
        let vec = self
            .values()
            .iter()
            .zip(condition.values().iter())
            .filter(|(_, y)| **y)
            .map(|(x, _)| x.clone())
            .collect();
        // TODO: Report bug of below codes.
        let cond = condition.values();
        let hset = self
            .na_indexes()
            .iter()
            .filter(|&x| cond[*x])
            .map(|x| x.clone())
            .collect();
        List::_new(vec, hset)
    }

    fn na_indexes(&self) -> Ref<HashSet<usize>>;
    fn na_value(&self) -> T;
    fn values(&self) -> Ref<Vec<T>>;
}
```
sub traits 1
```Rust
pub struct StringList {
    _values: RefCell<Vec<String>>,
    _na_indexes: RefCell<HashSet<usize>>,
}

#[pymethods]
impl StringList {
    #[new]
    pub fn new(vec: Vec<String>, hset: HashSet<usize>) -> Self {
        List::_new(vec, hset)
    }

    pub fn filter(&self, condition: &BooleanList) -> Self {
        List::filter(self, condition)
    }
}

impl List<String> for StringList {
    fn _new(vec: Vec<String>, hset: HashSet<usize>) -> Self {
        Self {
            _values: RefCell::new(vec),
            _na_indexes: RefCell::new(hset),
        }
    }

    fn na_indexes(&self) -> Ref<HashSet<usize>> {
        self._na_indexes.borrow()
    }

    fn na_value(&self) -> String {
        "".to_string()
    }

    fn values(&self) -> Ref<Vec<String>> {
        self._values.borrow()
    }
}

```

sub traits 2
```Rust
#[pyclass]
pub struct BooleanList {
    _values: RefCell<Vec<bool>>,
    _na_indexes: RefCell<HashSet<usize>>,
}

#[pymethods]
impl BooleanList {
    #[new]
    pub fn new(vec: Vec<bool>, hset: HashSet<usize>) -> Self {
        List::_new(vec, hset)
    }
}

impl List<bool> for BooleanList {
    fn _new(vec: Vec<bool>, hset: HashSet<usize>) -> Self {
        Self {
            _values: RefCell::new(vec),
            _na_indexes: RefCell::new(hset),
        }
    }

    fn na_indexes(&self) -> Ref<HashSet<usize>> {
        self._na_indexes.borrow()
    }

    fn na_value(&self) -> bool {
        false
    }

    fn values(&self) -> Ref<Vec<bool>> {
        self._values.borrow()
    }
}
```

Python wrapper class and constructor:
```Python
class UltraFastList:
    def __init__(self, values: LIST_RS) -> None:
        if type(values) is BooleanList:
            self.dtype = "bool"
        elif type(values) is StringList:
            self.dtype = "string"
        else:
            raise TypeError("...")
        self._values = values

    def filter(self, condition: "UltraFastList") -> "UltraFastList":
        assert isinstance(condition._values, BooleanList)
        return UltraFastList(self._values.filter(condition._values))

def from_seq(obj: Sequence, dtype: str) -> UltraFastList:
    na_indexes = set([i for i, x in enumerate(obj) if x is None])
    if dtype == "bool":
        cls = BooleanList
        na_val = False
    elif dtype == "string":
        cls = StringList
        na_val = ''
    else:
        raise ValueError("...")
    elements = [x if x is not None else na_val for x in obj]
    result = UltraFastList(cls(elements, na_indexes))
    return result
```
Compile and run the Python scripts below:
```Python
>>> import ulist as ul
>>> arr = ul.from_seq(['foo', None, 'bar',  None], dtype='string')
>>> arr
UltraFastList(['foo', None, 'bar', None])
>>> cond = ul.from_seq([True, False, True, False], 'bool')
>>> arr.filter(cond)
UltraFastList(['foo', 'bar'])
```
Everything works fine~

But if run the Python scripts below:
```Python
>>> arr = ul.from_seq(['foo', None, 'bar',  None], dtype='string')
>>> cond = ul.from_seq([True, False, False, True], 'bool')
>>> arr.filter(cond)
```
It raised `malloc: *** error for object 0x2000000000001: pointer being freed was not allocated` error.
Is there any suggestions and what should I do?

Some information might be useful:

- The Rust codes can compile without any error;
- There is nothing unsafe;
- PYO3 version = "0.16.4"
- System is MacOS Big Sur
- Python version 3.8
- Full codes are in this [branch](https://github.com/tushushu/ulist/tree/wip-fix-na)

There are also `Segmentation fault` errors caused by IntList and FloatList dtype filter method, which share the same trait `List`.</div>

**Comment by tushushu** [comment] 2022-05-03 12:28
@mejrs I found that sometimes it works, sometimes it crashes. Running the `arr.filter(cond)` line for multiple times can "help" to reproduce the errors.
----------------------------------------------------------------------------------------
Run the 3 steps below to reproduces the bug.

Git clone this [branch](https://github.com/tushushu/ulist/tree/wip-fix-na)
Run cd ulist && maturin develop
Run the codes below in ipython environment.
import ulist as ul
>>> arr = ul.from_seq(['foo', None, 'bar',  None], dtype='string')
>>> cond = ul.from_seq([True, False, False, True], 'bool')
>>> arr.filter(cond)

**Comment by tushushu** [comment] 2022-05-03 12:37
@mejrs And if you do not have a MacOS, you can folk my repo and run the CI [here](https://github.com/tushushu/ulist/blob/main/.github/workflows/main.yml), which will run the unit tests in MacOS, Ubuntu and Windows.

**Comment by tushushu** [comment] 2022-05-03 12:43
Also put my own PR here, https://github.com/tushushu/ulist/pull/163

**Comment by mejrs** [comment] 2022-05-03 14:55
Ah, it fails for all platforms: https://github.com/mejrs/ulist/actions/runs/2264489065 Could just be my windows being dumb

**Comment by mejrs** [comment] 2022-05-03 18:23
I reduced to:

```python
from ulist.constructor import StringList, BooleanList

elements = ['foo', '', 'bar',  '']
na_indexes = set([1,3])
arr = StringList(elements, na_indexes)

elements = [True, False, False, True]
na_indexes = set([1,2])
cond =  BooleanList(elements, na_indexes)

ret = arr.filter(cond)
                
ret.to_list()
```
(may need to run several times for it to fail)

It crashes when `to_list` overruns a buffer at https://github.com/tushushu/ulist/blob/main/ulist/src/base.rs#L244 So I believe this is not a bug in pyo3.

**Comment by tushushu** [comment] 2022-05-04 00:36
@mejrs Thanks for debugging, but the cond should have a empty set as na_indexes because there is no missing value in it. I can revise your scripts and try running it later.

**Comment by davidhewitt** [comment] 2022-05-04 00:51
I suggest switching all the `unsafe` and  `get_unchecked_mut` for regular indexing and see if you get panics. That should be a quick test to confirm whether there really is an overflow there.

**Comment by tushushu** [comment] 2022-05-04 02:15
Thanks @davidhewitt @mejrs 
Before changing the `get_unchecked_mut` to regular indexing.
```Python
>>> import ulist as ul
>>> arr = ul.from_seq(['foo', None, 'bar',  None], dtype='string')
>>> cond = ul.from_seq([True, False, False, True], 'bool')
>>> ret = arr.filter(cond)
>>> l = ret.to_list()
Go `pointer being freed was not allocated!` Error.
``` 

After switching the `get_unchecked_mut` for regular indexing as below.
```Rust
// let ptr = unsafe { vec.get_unchecked_mut(*i) };
// *ptr = None;
vec[*i] = None;
```
And run the Python script again, I got `pyo3_runtime.PanicException: index out of bounds: the len is 2 but the index is 3`. The bug is not caused by PYO3. Thanks so much for your help~

**Comment by davidhewitt** [comment] 2022-05-04 03:54
Thanks @mejrs for figuring this one out! Always worth checking we don't have a subtle bug in PyO3. I'll close this one for now 👍

**Closed by davidhewitt** 2022-05-04 03:54 UTC
Labels: bug, Unsound
