### ISSUE TITLE
Sometimes only adding the pyo3 deps will get the open ssl version link error

### ISSUE THREAD

**Issue by cpcs** [PyO3/pyo3#2571] opened 2022-08-21 04:17 UTC
### Bug Description

I saw this when only adding the deps without changing any code and run cargo test.

error: could not compile `crypto-client` due to previous error
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcFjAMKv/symbols.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.13n9wumdc5ct25eg.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.1indax54t4naf27i.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.1jwls8sx7uecmabn.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.24nqrhpjlyc83gfj.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.2qrim9cwty6olfux.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.2xr1wkn6fgvj9r11.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.3usxqi8tleinjc6r.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.3yk70g313ttw07wq.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.46iq4qp8lo0cry0j.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.4a7yaqt2b2si4bs2.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.4v3x6ij5l01c1zh0.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.4xicz6bb4nubtv2j.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.4zjufj7r1jrshyr1.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.50ka7e15jinzr7ia.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.a1qnhhjswxsrdb3.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.h2jt04l7k8v77mw.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.kx4ctx7dqbzu83a.rcgu.o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26.4ddwgaubauwuwb12.rcgu.o" "-Wl,--as-needed" "-L" "/local_datadir/github/crypto-client/target/debug/deps" "-L" "/opt/conda/lib" "-L" "/local_datadir/github/crypto-client/target/debug/build/ring-cfe4dad9e4e90f9f/out" "-L" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-ab2e32025d46bb5f.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-cc847bc948ac17c2.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-3c8611dc1b2b6848.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-0e61dad6fd10b568.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libcrypto_client-340863cd8c5fddd4.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libchrono-30fb0dad7109cb55.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libiana_time_zone-5a7fe6357b2a79db.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libnum_integer-853ae325bec373f8.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libnum_traits-cf0e9ef357821d68.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtime-a57fa9f74859ecd5.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libring-03f4bfa0ed91b39c.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libspin-2c2d0e97c8363747.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libuntrusted-bae7ad9dbbebb2b7.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libdata_encoding-3c374c1dd97708e3.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libreqwest-77167436fab96d01.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libhyper_tls-163ab924b52cc08d.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libipnet-c0c74975542ca8c3.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtokio_native_tls-d26d9bbd8192afe0.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libserde_urlencoded-126b604fb044aafe.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libmime-f9513972171bf326.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libencoding_rs-c44de9e887279379.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libnative_tls-f579b20183d2a36b.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libopenssl_probe-9fb528d4b515d117.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libopenssl-d46190e23efe6f84.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libbitflags-05dfd5b5d1225bed.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libforeign_types-46b9b5ebdcb273c8.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libforeign_types_shared-ecd28e6fe5f7182e.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libopenssl_sys-ce1d1bfca841d500.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libhyper-0b321fcd61a7d107.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libwant-dcafab768cc040e9.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtry_lock-febba4674ec63f92.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libhttparse-f04add0618484537.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libh2-6168ebf84946e70a.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtokio_util-db3f28b6f506e2e2.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libfutures_sink-572fee003e92af57.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtower_service-2e945a9ae7b7ce84.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtracing-16e3bb464a85bbb1.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtracing_core-d986e19f5b7c0711.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libonce_cell-1f5534b23b172a64.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libfutures_channel-58f099d19ce1adc7.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtokio-a2304903f5e334b9.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libnum_cpus-3db3216c15c04cf7.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libsocket2-9d70efb17e0ea460.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libmio-1b4c591bdc8c4d18.rlib" "/local_datadir/github/crypto-client/target/debug/deps/liblibc-e1c27bc548d6aea8.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libhttp_body-e925d73d842a509c.rlib" "/local_datadir/github/crypto-client/target/debug/deps/liblog-1f281fe8445d426c.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libcfg_if-90e3626e3c41eec3.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libfutures_util-4d1d7014bd5a8491.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libmemchr-4fce41623cec2314.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libfutures_io-17d3675bb391ad06.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libslab-bfbdb28742077af7.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libpin_project_lite-f2671a56a138cdc1.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libfutures_task-f987fea76d70a32c.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libpin_utils-b7ff504f33cec58a.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libfutures_core-0d0b7b3c5a10e702.rlib" "/local_datadir/github/crypto-client/target/debug/deps/liblazy_static-b33cd6b8ee13db74.rlib" "/local_datadir/github/crypto-client/target/debug/deps/liburl-0011768a44ab7863.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libidna-c8e8eaa5821b251d.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libunicode_normalization-7f15f9a7ed791153.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtinyvec-32c6f9102bb2f7e8.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libtinyvec_macros-ef06cf556416b731.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libunicode_bidi-96858afa72c3ee66.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libform_urlencoded-1a48ab4b6760ee48.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libpercent_encoding-b196e1663297fef1.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libmatches-a104dd362fa85146.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libhttp-ad9c989e5999360f.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libbytes-5e6b89f5bbd0cc67.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libfnv-22cd72556da4b99c.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libsimple_error-2e032285ab3ecdb6.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libcrypto_market_type-ad0b56069ae1ffc9.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libstrum-18c71eec6fb540af.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libserde_json-cbfa8448f79e6632.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libryu-35a1e8785e2c84ef.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libitoa-8f7e72094391218a.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libindexmap-c6a0d2b9f1b23663.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libhashbrown-e520009dc7a7a6ee.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libserde-065dee34af030d2e.rlib" "/local_datadir/github/crypto-client/target/debug/deps/libbase64-4563507a4eb0b4b2.rlib" "-Wl,--start-group" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-72269a4525d4f5cf.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-28d8f1c01a28b12d.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-5b78018a9f8ae4bc.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-f4160de9657f17b2.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-1cd8b958acdf2395.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-a4c4a7e7edfa8aea.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-061c02acc74ada37.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-2aed706f056a5dfb.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-1e1f90ff4bfdca6f.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-2d16c932daf0ad41.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-8f15fae89f489a33.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-81f3d85dace75e64.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-e071db8735f10456.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6db7e05a8de4df10.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-7c03f666869e802a.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-2a6a2797f7a73818.rlib" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0e3656b1fda5fd7b.rlib" "-Wl,--end-group" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b09abe545ed38eb1.rlib" "-Wl,-Bdynamic" "-lssl" "-lcrypto" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/opt/rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/local_datadir/github/crypto-client/target/debug/deps/kucoin-2fe7d7a460af3e26" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /local_datadir/github/crypto-client/target/debug/deps/libopenssl-d46190e23efe6f84.rlib(openssl-d46190e23efe6f84.openssl.0b0b24f0-cgu.3.rcgu.o): in function `openssl::error::Error::get':
          /home/cpcs/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.41/src/error.rs:115: undefined reference to `ERR_get_error_all'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

### Steps to Reproduce

Just add pyo3 deps in cargo.toml
run cargo test

### Your operating system and version

unbuntoo

### Your Python version (`python --version`)

3.9.9

### Your Rust version (`rustc --version`)

1.63.0

### Your PyO3 version

0.14

### How did you install python? Did you use a virtualenv?

No

**Comment by davidhewitt** [comment] 2022-08-21 05:13
Are you able to share a reproduction of this? To be honest it sounds like you've got your ssl link configuration slightly wrong rather than a PyO3 issue, however with a repro I'm happy to double-check.

**Comment by davidhewitt** [comment] 2022-08-21 05:17
`-L" "/opt/conda/lib"` - if I had to guess, maybe you've got a conda environment which has an incompatible openssl version installed in it, and that's what's causing the problem?

**Comment by davidhewitt** [comment] 2022-08-23 21:01
It will be PyO3 which is adding that to the library search path, because it needs to link to `libpython` to run the tests, and it's using the one from your conda environment because that was the active Python install which was found.

If that's a problem, the solution is to construct your environment differently (as you have done by modifying your profile), or by using [PYO3_CONFIG_FILE](https://pyo3.rs/v0.16.4/building_and_distribution.html#advanced-config-files) to specify a different lib dir.

Will close this issue, as I think the problem is understood and it's not something which PyO3 can change to avoid.

**Closed by davidhewitt** 2022-08-23 21:01 UTC
Labels: bug
