### ISSUE TITLE
Default arguments on methods causing crashes

### ISSUE THREAD

**Issue by sebpuetz** [PyO3/pyo3#514] opened 2019-06-20 22:22 UTC
### 🌍 Environment

 - Your rust version (`rustc --version`): nightly 1.36
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Tested with both 0.6 and 0.7

### 💥 Reproducing

Compilation (both through pyo3-pack and `cargo build` fails with an error when defining default string args to pymethods. `bool` and `usize` args are parsed correctly.

```Rust
#[pyclass]
struct Foo{
    inner: String
}

#[pymethods]
impl Foo {
    #[args(bar="test", limit = 10)]
    fn foo(&mut self, bar: &str, limit: usize, py: Python) -> PyResult<()> {
        self.inner = bar.to_string();
        Ok(())
    }
}
```

```
error[E0425]: cannot find value `test` in this scope
  --> src/lib.rs:37:1
   |
37 | #[pymethods]
   | ^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `finalfusion`.
```

If the default parameter doesn't match any of the actual parameters, the example compiles:

```Rust
#[pyclass]
struct Foo{
    inner: String
}

#[pymethods]
impl Foo {
    #[args(foo="test", limit = 10)]
    fn foo(&mut self, bar: &str, limit: usize, py: Python) -> PyResult<()> {
        self.inner = bar.to_string();
        Ok(())
    }
}
```

**Comment by kngwyu** [comment] 2019-06-21 03:16
Thanks for reporting!
Looks it's a bug in our proc macro code :thinking:

**Comment by sebpuetz** [comment] 2019-06-21 07:08
I was also looking into `Vec` as default argument, judging by the documentation, it should be possible to do something along these lines:
```Rust
    #[args(bar=vec![false, false, false], limit = 10)]
    fn foo(&mut self, bar: Vec<bool>, limit: usize, py: Python) -> PyResult<()> {
        Ok(())
    }
```

This crashes with the same message as above. Is this intended or should this compile if the bug in the macro is fixed?

**Comment by kngwyu** [comment] 2019-06-21 07:21
@sebpuetz 
I think `bar = "string` should be fixed but `vec!` can't be there because **proc macro backend cannot parse it**, though it should be possible to pass `'vec![]'`.

**Comment by birkenfeld** [comment] 2019-06-21 07:25
I think this is working as intended; strings are taken as code. So it should be `"\"test\""` and `”vec![...]"`.

This is precisely due to the limitation that attributes cannot contain arbitrary rust code (or at least, it is made very difficult, can't remember the exact state of things here).

**Comment by sebpuetz** [comment] 2019-06-21 07:37
Thanks for the heads-up! Both work with your proposed solutions, I wasn't aware I had to pass the code as string literals to the attribute!

**Comment by kngwyu** [comment] 2019-06-21 07:39
Yeah, we as noted [here](https://doc.rust-lang.org/reference/attributes.html) what we can take as an argument in attributes is only LiteralExpression, though I think it's still possible to pass `arg="str"` as string by checking the argument type.

**Comment by sebpuetz** [comment] 2019-06-21 07:40
Thanks for the quick resolution, I guess I should read up on attributes.

**Comment by kngwyu** [comment] 2019-06-21 07:59
After looking the code for a while, I came to the conclusion that it is difficult to support
```rust
#[args(test = "test")]
fn function(&self, test: &str){}
```
syntax in pymethods.

Please use `test = "\"test\""`.

**Closed by kngwyu** 2019-06-21 07:59 UTC
