### ISSUE TITLE
ImportError: dynamic module does not define init function

### ISSUE THREAD

**Issue by msanders** [PyO3/pyo3#144] opened 2018-04-29 23:47 UTC
Hi, I'm seeing the following error when compiling modules on the latest nightly:

```
error[E0658]: paths of length greater than one in macro invocations are currently unstable
  --> src/lib.rs:50:3
   |
50 | #[py::modinit(_word_count)]
   |   ^^^^^^^^^^^
   |
   = help: add #![feature(proc_macro_path_invoc)] to the crate attributes to enable
```

Then once I fix that by adding the feature attribute, I get an error when importing e.g. `python -c "import word_count"` from https://github.com/PyO3/pyo3/tree/master/examples/word-count:

```
Python 2.7.14 (default, Apr  4 2018, 09:03:23) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import word_count
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "word_count/__init__.py", line 4, in <module>
    from ._word_count import search, search_sequential
ImportError: dynamic module does not define init function (init_word_count)
```

Can repro by running:
```
cd examples/word-count
python setup.py develop
python -c "import word_count"
```

(happens on both Python 2 and 3)

Any ideas?

**Comment by konstin** [comment] 2018-05-01 22:44
Yep, it's caused by rust-lang/rust#50120 and fixed in https://github.com/PyO3/pyo3/pull/147, which will be included in the next release.

**Closed** 2018-05-05 15:02 UTC
Labels: bug
