### ISSUE TITLE
Serde-like deserialization for Python to Rust?

### ISSUE THREAD

**Issue by vedantroy** [PyO3/pyo3#1488] opened 2021-03-12 01:48 UTC
Is there serde-like deserialization to convert Python objects to Rust?

Something like:

```rust
struct Foo(String, String);

// x is of type `PyAny`
let rustTuple: &Foo = x.as_rust_obj().unwrap();
```

**Comment by messense** [comment] 2021-03-12 08:59
See https://github.com/davidhewitt/pythonize

**Comment by messense** [comment] 2021-03-12 09:01
Closing as a duplicate of https://github.com/PyO3/pyo3/issues/566

**Closed by messense** 2021-03-12 09:01 UTC
