### ISSUE TITLE
#[pyclass] over enum is missing python's name and value attributes

### ISSUE THREAD

**Issue by softstream-link** [PyO3/pyo3#3791] opened 2024-02-03 04:44 UTC
```rust
#[pyclass]
#[derive(Debug, Clone)]
pub enum ConType {
    Initiator,
    Acceptor,
}
```

equivalent

```python
class ConType(enum.Enum):
    Initiator = enum.auto()
    Acceptor = enum.auto()
```

however when defined in python can be used as:

```python
con_type = ConType.Initiator
print(f'{con_type.name}, {con_type.value}')
```

but if only defined using pyo3 rust calling `name` and `value` attributes fail

**Comment by davidhewitt** [comment] 2024-02-03 08:04
I think this is a duplicate of #2887 

That issue has a summary of what we think needs to happen to improve this, PR welcome to help!

**Closed by davidhewitt** 2024-02-03 08:04 UTC
