### ISSUE TITLE
[0.21.1] Compilation error if async method has more than 2 args

### ISSUE THREAD

**Issue by rigens** [PyO3/pyo3#4044] opened 2024-04-03 14:20 UTC
### Bug Description

```
error: expected one of `.`, `;`, `?`, `else`, or an operator, found keyword `let`
  --> src/lib.rs:12:1
   |
12 | #[pymethods]
   | ^^^^^^^^^^^^ expected one of `.`, `;`, `?`, `else`, or an operator
   |
   = note: this error originates in the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Steps to Reproduce

```rust
#[pyclass]
pub struct MyClass {}

#[pymethods]
impl MyClass {
    pub async fn my_method(&self, a: u64, b: u64) -> u64 {
        a + b
    }
}
```

If remove the third argument, it compiles successfully

### Your operating system and version

Ubuntu 22.04

### Your Python version (`python --version`)

Python 3.12.2

### Your Rust version (`rustc --version`)

Python 3.12.2

### Your PyO3 version

pyo3 = {version = "0.21.1", features = ["full"]}

### How did you install python? Did you use a virtualenv?

...

**Comment by LilyFoote** [comment] 2024-04-03 14:39
This looks like a duplicate of #4034 to me. The fix will be in `0.21.2`.

**Closed by LilyFoote** 2024-04-03 14:39 UTC
