### ISSUE TITLE
error importing module: AttributeError: class must define a '_type_' attribute

### ISSUE THREAD

**Issue by xiyuzhai** [PyO3/pyo3#4797] opened 2024-12-13 19:48 UTC
### Bug Description

Hi, all. This is a beginner in pyo3 speaking. I'm trying to call python from Rust. But it failed to import a python module, although its content has been reduced to just "import spacy" (spacy is a commonly used python package for natural language processing).

It's fine with importing other packages like sys os etc.

Minimal reproducible example: https://github.com/xiyuzhai/pyo3-question.

### Steps to Reproduce

To replicate,

First,
```
make venv
```
to create a new local virtual python environment with spacy.

Then,
```
source venv/bin/activate
```
to activate the virtual python environment.

Lastly,
```
make run
```
to see the error
```
thread 'main' panicked at src/main.rs:15:48:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'AttributeError'>, value: AttributeError("class must define a '_type_' attribute"), traceback: Some(<traceback object at 0x7f2553c45700>) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is the same steps as in the readme I've written in https://github.com/xiyuzhai/pyo3-question.

### Backtrace

```shell
thread 'main' panicked at src/main.rs:15:48:
called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'AttributeError'>, value: AttributeError("class must define a '_type_' attribute"), traceback: Some(<traceback object at 0x733ff7649740>) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
   3: core::result::Result<T,E>::unwrap
             at /home/xiyuzhai/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1104:23
   4: pyo3_question::main::{{closure}}
             at ./src/main.rs:15:9
   5: pyo3::marker::Python::with_gil
             at /home/xiyuzhai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.23.3/src/marker.rs:412:9
   6: pyo3_question::main
             at ./src/main.rs:4:5
   7: core::ops::function::FnOnce::call_once
             at /home/xiyuzhai/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Your operating system and version

Ubuntu 24.04

### Your Python version (`python --version`)

Python 3.12.8

### Your Rust version (`rustc --version`)

rustc 1.83.0

### Your PyO3 version

0.23.3

### How did you install python? Did you use a virtualenv?

virtualenv.

I use makefile:
```
venv:
	python -m venv .venv
	. .venv/bin/activate && pip install spacy
```

**Comment by ngoldbaum** [comment] 2024-12-13 20:49
I'm not able to reproduce this on Python 3.12.8 on my mac:

```
goldbaum at Nathans-MBP in ~/Documents/pyo3-question on main
± make
cargo run
    Updating crates.io index
     Locking 19 packages to latest compatible versions
   Compiling target-lexicon v0.12.16
   Compiling once_cell v1.20.2
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling libc v0.2.168
   Compiling autocfg v1.4.0
   Compiling heck v0.5.0
   Compiling cfg-if v1.0.0
   Compiling unindent v0.2.3
   Compiling indoc v2.0.5
   Compiling memoffset v0.9.1
   Compiling quote v1.0.37
   Compiling syn v2.0.90
   Compiling pyo3-build-config v0.23.3
   Compiling pyo3-ffi v0.23.3
   Compiling pyo3-macros-backend v0.23.3
   Compiling pyo3 v0.23.3
   Compiling pyo3-macros v0.23.3
   Compiling pyo3-question v0.1.0 (/Users/goldbaum/Documents/pyo3-question)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.76s
     Running `target/debug/pyo3-question`

goldbaum at Nathans-MBP in ~/Documents/pyo3-question on main
± python -VV
Python 3.12.8 (main, Dec 13 2024, 13:47:52) [Clang 16.0.0 (clang-1600.0.26.6)]

goldbaum at Nathans-MBP in ~/Documents/pyo3-question on main
± python -c "import spacy; print(spacy.__version__)"
3.8.3
```

**Comment by xiyuzhai** [comment] 2024-12-13 22:11
I see. Let me try on my other pcs.

**Comment by xiyuzhai** [comment] 2024-12-13 22:21
<img width="1280" alt="Screenshot 2024-12-13 at 2 20 03 PM" src="https://github.com/user-attachments/assets/ab059990-db9f-449f-8a17-93856abf6412" />

I'm seeing the same error on my Macbook Pro. Does it have something to do with wifi, lol.

**Comment by xiyuzhai** [comment] 2024-12-13 22:23
Lol. It works on my Macbook Pro.

**Comment by ngoldbaum** [comment] 2024-12-13 22:28
Hmm I can try on Ubuntu...

**Comment by xiyuzhai** [comment] 2024-12-13 22:31
I guess something is wrong when I created the venv.

**Comment by xiyuzhai** [comment] 2024-12-13 22:34
I'm quickly investigating this. It seems that it may have something to do with python version. It might look like when I use python 3.12.8 in vscode, things go bad. When I use python 3.12.3 in alacritty, things are normal.

Let me make an exhaustive investigation.

**Comment by xiyuzhai** [comment] 2024-12-13 22:35
> Hmm I can try on Ubuntu...

Thanks. I'm actually on ubuntu now. I dual boot windows and ubuntu.

**Comment by ngoldbaum** [comment] 2024-12-13 22:37
I'm not able to reproduce this on my Ubuntu Python 3.12.8 setup either. I also suspect this has something to do with your Python setup on the affected machine.

**Comment by xiyuzhai** [comment] 2024-12-13 22:37
> I'm not able to reproduce this on my Ubuntu Python 3.12.8 setup either. I also suspect this has something to do with your Python setup on the affected machine.

I agree with you!

**Comment by ngoldbaum** [comment] 2024-12-13 22:39
Closing since it looks like this isn't a pyo3 issue.

**Closed** 2024-12-13 22:39 UTC
Labels: bug

**Comment by xiyuzhai** [comment] 2024-12-13 22:44
Yeah, it seems to do with my pyenv setup.
