### ISSUE TITLE
Possible memory leak(?) in version 0.22

### ISSUE THREAD

**Issue by davidlougheed** [PyO3/pyo3#4630] opened 2024-10-18 15:01 UTC
Hello,

I have a Rust library for some Python code I'm working on (https://github.com/davidlougheed/strkit_rust_ext , I realize this has many functions and so this doesn't narrow much down) that in 0.22 blows up memory usage (~2.3 GB) vs. ~300 MB for 0.21.

This seems to come from code which only compiled because `gil-refs` was enabled, so it is maybe a real error on my part that was being masked: the following diff seems to address it somewhat: https://github.com/davidlougheed/strkit_rust_ext/commit/b4ee3b15806aa75beabf4f1a7568fc704da38dca

I'm still fairly new to Rust, so I'm sure there's some ugly stuff I'm doing in there.

**Comment by davidhewitt** [comment] 2024-10-18 15:28
Have you got a minimal reproducer of the problem? I don't see anything obvious from scanning that patch you link above.

**Comment by davidlougheed** [comment] 2024-10-18 15:29
I'll see what I can do to replicate it!

**Comment by mejrs** [comment] 2024-10-18 15:36
Do you have a memory leak or is it just using a lot of memory?

**Comment by mejrs** [comment] 2024-10-18 15:37
I also don't see anything obvious but there are some gil-ref related usage patterns that can result in something that looks like it's leaking memory.

**Comment by davidlougheed** [comment] 2024-10-18 15:38
maybe not a true memory leak, but no, it's a very stark difference between 0.21 and 0.22 – i use a "lot" of memory before (300 MB to process 5000 items in my tool), but it goes to the number I mentioned above (2.3 GB) with 0.22. I'm working on a reproduction now but it may take me a little bit.

**Comment by LilyFoote** [comment] 2024-10-18 15:42
It might be useful to use a memory profiler. I've had a lot of success with https://github.com/KDE/heaptrack.

**Comment by davidlougheed** [comment] 2024-10-18 16:00
Weirdly enough after some testing it happens when I enable the `gil-refs` feature on 0.22 with 0 code changes. I'll look into profiling next.

**Comment by davidlougheed** [comment] 2024-10-18 16:38
same code, PyO3 0.22, using `memray` for memory profiling:

`gil-refs` off:

<img width="1908" alt="image" src="https://github.com/user-attachments/assets/70a52508-7bf3-4cd1-bd46-cae7283d5dc1">

`gil-refs` on:

<img width="1915" alt="image" src="https://github.com/user-attachments/assets/bb622656-bf2f-4618-97af-4c41ea849e06">

**Comment by davidlougheed** [comment] 2024-10-18 17:30
I'm having some trouble making a small-enough reproducible example, so I'll pick it up later.

**Comment by davidhewitt** [comment] 2024-10-18 20:09
Hmm, so it's fixed by removing the `gil-refs` feature? In that case, I'd just encourage you to keep the feature off and suggest there's no further action on our part here, we've completely removed that feature in the upcoming 0.23 release 😄

In general, the `gil-refs` caused higher memory usage than necessary, e.g. #319, #1056. It's a bit of a surprise that this got worse with 0.22, but that's also not impossible as we were in the process of decommissioning that feature and were testing it / optimising for the future, not for those code paths.

**Comment by davidlougheed** [comment] 2024-10-18 20:11
yes I've just removed it – if it's getting removed completely, I won't worry about debugging any further (but maybe someone else will find this conversation useful haha)

**Closed** 2024-10-19 10:09 UTC
