### ISSUE TITLE
Flaky datetime test

### ISSUE THREAD

**Issue by Alexander-N** [PyO3/pyo3#720] opened 2020-01-11 00:37 UTC
The test `test_datetime_check` fails from time to time with an error like
```
---- test_datetime_check stdout ----
thread 'test_datetime_check' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: Py(0x60d15300, PhantomData) }', src\libcore\result.rs:1192:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
It could be that this occurs only on Windows with Python 3.6: https://github.com/PyO3/pyo3/pull/719/checks?check_run_id=384307686 and https://github.com/PyO3/pyo3/pull/651#issuecomment-546640959.

@pganssle Do you have any idea what could cause this?

**Comment by davidhewitt** [comment] 2020-01-12 08:23
When developing pyO3 on Windows with 3.8 the test wobbles for me occasionally too.

**Comment by pganssle** [comment] 2020-01-12 13:16
This is a real head-scratcher. I would expect possible "flakiness" for the hypothesis-based tests based on rare edge-cases, but `test_datetime_check` should be entirely deterministic (and not dependent on platform, either). That test just constructs a few `datetime` subclasses and calls the "check" functions on them, pretty dead simple.

Maybe we should start running the tests with `RUST_BACKTRACE=1`, so we can get a bit more info in hard-to-repro cases like this?

My immediate possible thoughts are some sort of thread-safety issue or possibly another test setting the Python exception state and returning without failing to check it (which would then raise an exception in whatever the next thing to run is that sets the exception state).

One possibility is that this is bleeding over from some issue with [these out-of-bounds tests](https://github.com/PyO3/pyo3/blob/68726f9674d4c79b0437ce559af4964347f82b12/tests/test_datetime.rs#L146), but that shouldn't be Windows-specific.

**Comment by davidhewitt** [comment] 2020-01-22 21:45
I had this fail on me on CI earlier today. I think it was in a Linux environment?!

https://github.com/davidhewitt/pyo3/commit/43df3299abc3cfdf006914c44d5b7f3d0a987f6c/checks?check_suite_id=414584878

**Comment by pganssle** [comment] 2020-01-22 22:09
> I had this fail on me on CI earlier today. I think it was in a Linux environment?!

I don't think so - maybe WSL or something, but a lot of the paths use `\` as a separator.

I can't really make heads or tails of that backtrace. I guess what's happening is that *something* in [`_get_subclasses`](https://github.com/PyO3/pyo3/blob/d2174c2eadab7879255a6be51046eff83e22e646/tests/test_datetime.rs#L8) is breaking, but `PyResult` is `Result<..., ()>`, so `?` doesn't seem to propagate anything about the inner error (not even the line it's on :().

I assume it's some sort of thread-safety issue. Maybe `py.import("datetime")?` isn't as thread-safe as we thought? That's the only thing in there that would obviously mutate any global variable.

Anyone with a Windows machine want to try and make this slightly more reproducible? It might help to use a [Barrier](https://doc.rust-lang.org/std/sync/struct.Barrier.html) in all the different test functions to try and more readily induce race conditions.

We might be able to make this less flaky by locking around `_get_subclasses` or around whatever subset of the test has the race condition, but it's a bit hard to confidently make a change like that without being able to reproduce the bug. Plus it would be good to know if the root cause is something to be addressed in PyO3 or something to warn people about in user code or something.

**Comment by davidhewitt** [comment] 2020-01-23 07:44
> but `PyResult` is `Result<..., ()>`

`PyResult` is `Result<..., PyErr>`, but the test has a `map_err(|e| e.print(py))` which is printing and throwing away the `PyErr`.

Frustratingly I can't see anywhere in that output the result of `e.print()` - maybe Python wrote to its output buffer but did not flush?!

**Comment by davidhewitt** [comment] 2020-01-23 07:48
> Anyone with a Windows machine want to try and make this slightly more reproducible? 

I'm tempted to run the test suite in a loop on my machine this morning and see how long it takes to get a failure 😅

**Comment by davidhewitt** [comment] 2020-01-23 09:06
I ran it for a bit and added some debug printing too.

There seems to be a race going on where multiple tests are making progress at the same time. This seems very odd given that all of the tests are supposedly acquiring the GIL... ?

    running 4 tests
    {'timedelta': <class 'datetime.timedelta'>}
    {'date': <class 'datetime.date'>}
    {'datetime': <class 'datetime.datetime'>}
    {'time': <class 'datetime.time'>}
    {'timedelta': <class 'datetime.timedelta'>, 'Subklass': <class '__main__.Subklass'>}
    {'date': <class 'datetime.date'>, 'Subklass': <class '__main__.Subklass'>}
    test test_delta_check ... {'datetime': <class 'datetime.datetime'>, 'Subklass': <class '__main__.Subklass'>}
    ok
    {'time': <class 'datetime.time'>, 'Subklass': <class '__main__.Subklass'>}
    test test_date_check ... FAILED
    test test_datetime_check ... FAILED
    test test_time_check ... FAILED

Gotta head to work now, but I might pick this up again at a later date...

**Comment by davidhewitt** [comment] 2020-01-23 11:08
...might be related to #288?

**Comment by pganssle** [comment] 2020-01-24 17:09
> There seems to be a race going on where multiple tests are making progress at the same time. This seems very odd given that all of the tests are supposedly acquiring the GIL... ?

This is an easy mistake to make (I made it when first building the `datetime` support), but when you create a `GILGuard` object with `acquire_gil`, you don't actually *hold* the GIL for the lifetime of object - what is guaranteed is that whenever your *Rust code* is executing you hold the GIL. Python and C functions are free to release the GIL, and in fact they will do so any time they, among other things, do an I/O operation like attempting to import a module.

This is important to keep in mind because it can lead to deadlocks if you attempt to layer on additional locking mechanisms - see [this comment about how we avoid deadlocks in datetime](https://github.com/PyO3/pyo3/blob/3d8b9a8e7b197d9a9b78ffed0bb31f8c853f1671/src/ffi/datetime.rs#L199).

With regard to "multiple tests making progress at the same time", I think that's perfectly fine, but it seems like maybe the issue is that in `_get_subclasses` we're overwriting what `Subklass` means (I'm not sure what namespace independent calls to `py.run` use, but it looks like maybe it's `__main__`)?

If that's the problem, I'm kinda surprised we haven't seen this problem before now, and that it's only happening on Windows machines. If that turns out to be the issue, it should be pretty simple to either give these things unique names or put them in a unique namespace.

**Comment by Alexander-N** [comment] 2020-02-01 16:12
> but it seems like maybe the issue is that in `_get_subclasses` we're overwriting what `Subklass` means (I'm not sure what namespace independent calls to `py.run` use, but it looks like maybe it's `__main__`)?
> 
> If that's the problem, I'm kinda surprised we haven't seen this problem before now, and that it's only happening on Windows machines. If that turns out to be the issue, it should be pretty simple to either give these things unique names or put them in a unique namespace.

I tried to make the names unique for each test: https://github.com/Alexander-N/pyo3/pull/3/files but the test still fails https://github.com/Alexander-N/pyo3/pull/3/checks?check_run_id=420934780.

**Comment by davidhewitt** [comment] 2020-02-01 18:09
> I tried to make the names unique for each test: https://github.com/Alexander-N/pyo3/pull/3/files but the test still fails https://github.com/Alexander-N/pyo3/pull/3/checks?check_run_id=420934780.

Strange. Also in the exception message I can't see the traceback being printed out, might need to run the tests with `PYTHONUNBUFFERED=1` environment variable?

**Comment by Alexander-N** [comment] 2020-02-01 20:11
Not sure if this is related to buffering, sometimes I get a NameError like:
```
NameError: name 'SubSubklassdatetime' is not defined
```
https://github.com/Alexander-N/pyo3/pull/3/checks?check_run_id=421093043

And sometimes not: https://github.com/Alexander-N/pyo3/pull/3/checks?check_run_id=421092950

**Comment by davidhewitt** [comment] 2020-02-01 22:12
Ah yeah, probably not buffering. It's `test_date_check` which failed in the one without a traceback, which doesn't have an `e.print()` statement in it.

I wonder, could it be some kind of ownership issue where these things have a zero reference count and are getting GC'd out from underneath us? I don't see how that could be possible though...

**Comment by Alexander-N** [comment] 2020-02-02 02:32
> I wonder, could it be some kind of ownership issue where these things have a zero reference count and are getting GC'd out from underneath us? I don't see how that could be possible though...

I think that's exactly whats happening. In my branch the error is also reproducible on Linux and does disappear if I comment out the releasing of owned objects when the GILGuard is dropped.
```rust
    pub unsafe fn drain(&mut self, _py: Python, owned: usize, borrowed: usize, pointers: bool) {
        // Release owned objects(call decref)
        // while owned < self.owned.len() {
        //     let last = self.owned.pop_back().unwrap();
        //     ffi::Py_DECREF(last.as_ptr());
        // }
        // Release borrowed objects(don't call decref)
        self.borrowed.truncate(borrowed);

        if pointers {
            self.release_pointers();
        }

        self.obj.clear();
    }
```

**Comment by davidhewitt** [comment] 2020-02-02 09:36
Oh crikey. I guess what must be happening is that when the first test finishes and drops its acquired `GILGuard`, the entire release pool gets drained even though other tests / threads are still reliant on the owned pointers in the pool.

A fix could potentially be to make the release pools thread-local? Or to have some kind of reference counting? If we eliminate the release pool as part of #679 then this might fix this too.

**Comment by Alexander-N** [comment] 2020-02-02 14:03
The error seems to occur only if python modules are imported. I think what happens is something along the lines of: The imports release the GIL and the wrong object is popped from the release pool. 

For example this reproduces it fairly consistently for me:
```rust
#[test]
fn test_release_race1() {
    let gil = Python::acquire_gil();
    let py = gil.python();
    println!("make ob1");
    let ob1 = py.eval("object()", None, None).unwrap();
    py.import("datetime").unwrap();
    py_run!(py, ob1, "print('ob1' + str(ob1))");
}

#[test]
fn test_release_race2() {
    let gil = Python::acquire_gil();
    let py = gil.python();
    println!("make ob2");
    let ob2 = py.eval("object()", None, None).unwrap();
    py.import("datetime").unwrap();
    py_run!(py, ob2, "print('ob2' + str(ob2))");
}
```

**Comment by Alexander-N** [comment] 2020-02-02 14:19
After reading https://github.com/PyO3/pyo3/issues/720#issuecomment-578217918 again, I'll try to make the idea clearer:
- ob1 gets put into the release pool
- the import releases the GIL temporarily
- test_release_race2 makes progress and ob2 gets put into the release pool
- test_release_race1 finishes and with dropping of it's GILGuard ob2 instead of ob1 is popped from the relase pool
- test_release_race2 fails because ob2 has been freed

Does this sound plausible?

**Comment by davidhewitt** [comment] 2020-02-02 14:21
This sounds exactly like what is going on to me. Presumably it would be possible to verify this ordering by adding a few more `println!` statements to your example.

**Comment by davidhewitt** [comment] 2020-02-02 14:22
Though I think:

> test_release_race1 finishes and with dropping of it's GILGuard ob2 instead of ob1 is popped from the relase pool

What actually happens is that both `ob2` and `ob1` are being freed.

**Comment by Alexander-N** [comment] 2020-02-02 14:30
> Though I think:
> 
> > test_release_race1 finishes and with dropping of it's GILGuard ob2 instead of ob1 is popped from the relase pool
> 
> What actually happens is that both `ob2` and `ob1` are being freed.

I thought that if there was one owned object in the release pool when the second test acquires it's GILGuard then `owned==1` and  the `while owned < self.owned.len()`  condition is in place to ensure that there is still one owned object after draining the release pool.

```rust
        while owned < self.owned.len() {
            let last = self.owned.pop_back().unwrap();
            ffi::Py_DECREF(last.as_ptr());
        }
```

**Comment by davidhewitt** [comment] 2020-02-02 15:32
Ah, sorry, yes, you're right! I should have read that code closer 😄

**Comment by kngwyu** [comment] 2020-02-03 08:53
@Alexander-N @davidhewitt  thank you for useful discussions!

> I think what happens is something along the lines of: The imports release the GIL and the wrong object is popped from the release pool.

OMG, it sounds serious problem to me :thinking:

**Comment by davidhewitt** [comment] 2020-02-03 09:34
Agreed! This seems like another reason to consider replacing the release pool with a better solution. (Along with #679)

**Comment by pganssle** [comment] 2020-02-03 14:01
This is quite a long thread now and it's sorta misleadingly titled since "Flaky datetime test" is just the proximate symptom, not the root problem to be solved. Might I suggest the following course of action:

1. Temporarily add a lock around the contents of the `_get_subclasses()` function, so that the `datetime` test is no longer flaky, with a `// TODO` comment to remove it when the problem is fixed.
2. Spawn a new issue with a succinct summary of the results of this thread and with the MWE that consistently reproduces the problem.

That way people won't get hit with erroneous failures, and if we lose momentum on solving this issue, there will be a cleaner "entry point" for new contributors rather than reading through a long thread ostensibly about a flaky test.

Good work everyone!

**Comment by Alexander-N** [comment] 2020-02-03 22:47
Good point, I opened #756.

**Comment by davidhewitt** [comment] 2020-04-12 10:45
I believe a workaround was introduced in #867, so I will close this for now and leave #756 open to track the fundamental issue.

**Closed by davidhewitt** 2020-04-12 10:45 UTC
Labels: Unsound, bug
