### ISSUE TITLE
allow `__setitem__` on `Hashmap`s when `#[pyo3(set)]` is specified

### ISSUE THREAD

**Issue by AntoineRR** [PyO3/pyo3#3026] opened 2023-03-08 22:09 UTC
Here is a small code snippet to explain what I am trying to achieve:

Rust:
```rust
use pyo3::{prelude::*, types::PyDict};
use std::collections::HashMap;

#[pyclass]
struct Dict(#[pyo3(get, set, name = "inner")] HashMap<String, String>);

#[pymethods]
impl Dict {
    #[new]
    fn new() -> Self {
        Self(HashMap::new())
    }
}

#[pyclass]
struct Dict2(#[pyo3(get, set, name = "inner")] Py<PyDict>);

#[pymethods]
impl Dict2 {
    #[new]
    fn new(py: Python) -> Self {
        Self(PyDict::new(py).into())
    }
}

#[pymodule]
fn pyo3_test(_py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_class::<Dict>()?;
    m.add_class::<Dict2>()?;
    Ok(())
}
```

Python:
```python
from pyo3_test import Dict, Dict2

print("dict")

test_dict = Dict()

print(test_dict.inner)
test_dict.inner["test"] = "hello"
print(test_dict.inner)
test_dict.inner = {"test2": "hello2"}
print(test_dict.inner)

print("dict 2")

test_dict_2 = Dict2()

print(test_dict_2.inner)
test_dict_2.inner["test"] = "hello"
print(test_dict_2.inner)
test_dict_2.inner = {"test2": "hello2"}
print(test_dict_2.inner)
```

Output:
```
dict
{}
{}
{'test2': 'hello2'}
dict 2
{}
{'test': 'hello'}
{'test2': 'hello2'}
```

As you can see, it seems the inner `Hashmap` of `Dict` cannot be modified through the `__setitem__` dunder method (i.e. `test_dict.inner["test"] = "hello"`) while it is doable for `PyDict`. Is it possible to enable the use of this method through `#[pyo3(set)]`?

**Comment by mejrs** [comment] 2023-03-09 12:50
It looks like you are running into https://pyo3.rs/v0.18.1/faq#pyo3get-clones-my-field

**Comment by AntoineRR** [comment] 2023-03-09 22:22
Thanks, that does make sense now. I checked and the getter is indeed called when running `test_dict.inner["test"] = "hello"`, which means we only modify a copy of the dict. I guess there is no way to achieve what I want without a `Py` wrapper then (so I'll have to use the GIL to interact with the field from Rust) :disappointed: Anyway thanks for linking to the relevant doc!

**Comment by davidhewitt** [comment] 2023-09-16 20:55
Closing as duplicate of #1358 

(It discusses classes rather than hash-map but the fundamental cause is the same.)

**Closed by davidhewitt** 2023-09-16 20:55 UTC
Labels: enhancement
