### ISSUE TITLE
Pyo3 may be unsound due to calls to `getenv`

### ISSUE THREAD

**Issue by xerxes12354** [PyO3/pyo3#1579] opened 2021-04-28 04:04 UTC
I was looking at the time crate wondering why the [time crate didn't give offsets](https://github.com/time-rs/time/issues/293), and I stumbled upon [this thread on Internals](https://internals.rust-lang.org/t/function-to-hold-lock-on-execution-environment-for-ffi/13702/22). This seems like a big problem so I went looking for FFI crates where this could be a problem.

Python is single threaded, so I thought this crate was immune, but another Rust-only thread that calls `set_env` while Python calls the `os.getenv()` method which dispatched straight to the C call. As such  this wrapper has a data race when `set_env` is called in another thread.

**Comment by davidhewitt** [comment] 2021-04-28 07:21
I mean, sure, but I don't think there's any reasonable mitigations which can be written in the PyO3 layer. The issue described is common to any multithreaded Rust program where at least one of the threads is interacting with a C library (including libc itself, as seen in https://github.com/rust-lang/rust/issues/27970).

Note that this issue only exists on unix systems where the underling libc implementation doesn't provide thread-safe primitives for accessing the environment.

The upstream discussion https://github.com/rust-lang/rust/issues/27970 is potentially a suitable place for users concerned with this to provide discussion (at least in the Rust context).

One could argue that Python also should not be modifying the environment, because the glibc stance (as I read it in https://sourceware.org/bugzilla/show_bug.cgi?id=13271) appears to be that multithreaded programs should not ever modify the environment. Sure, only a single Python thread can execute at a time, but the Python interpreter itself can have any number of threads running (e.g. from native extension modules) which could be reading the environment.

**Comment by davidhewitt** [comment] 2022-08-25 18:00
As discussed above, I don't think there is any mitigation which can be done at the PyO3 layer, and the upstream Rust discussion continues to move forward. I am going to close this issue, as while it is a valid concern, it is not specifically caused by this library nor something this library can do anything about.

**Closed by davidhewitt** 2022-08-25 18:00 UTC
Labels: blocked, Unsound
