### ISSUE TITLE
Use of #[pymethods] or #[pyfn] with borrowed args triggers clippy::borrow_deref_ref warning.

### ISSUE THREAD

**Issue by adam-azarchs** [PyO3/pyo3#2556] opened 2022-08-16 02:48 UTC
### Bug Description

Generated code for `#[pyfunction]` and related macros is triggering `clippy:bor

### Steps to Reproduce

For  example,
```rust
#[pymethods]
impl Thing {
    #[new]
    fn __new__(
        data: &PyArray1<f64>,
    ) -> Self {
        Thing {
            data: data.to_owned_array(),
        }
    }
}
```
Running clippy results in
```
warning: deref on an immutable reference
   --> src/lib.rs:129:15
    |
129 |         data: &PyArray1<f64>,
    |               ^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#borrow_deref_ref
help: if you would like to reborrow, try removing `&*`
    |
129 |         data: &PyArray1<f64>,
    |               ~
help: if you would like to deref, try using `&**`
    |
129 |         data: &**&PyArray1<f64>,
    |               ~~~~
```

### Your operating system and version

Linux

### Your Python version (`python --version`)

3.9.7

### Your Rust version (`rustc --version`)

1.63.0

### Your PyO3 version

0.16.5

### How did you install python? Did you use a virtualenv?

Not relevant.  Building with `PYO3_NO_PYTHON=1`.

**Comment by davidhewitt** [comment] 2022-08-16 06:21
Duplicate of #2555

**Closed by davidhewitt** 2022-08-16 06:21 UTC
Labels: bug
